#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#-------Scripts to run before git commit------

# Must contain no TS Error
pnpm tsc --noEmit

# Must pass all tests
pnpm test

# Lint staged files before commit
pnpm lint:staged
